spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce_db
    driver: com.mysql.cj.jdbc.Driver
    username: root
    password: admin
  liquibase:
    change-log: db/changelog/master.xml

