spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce_db
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  liquibase:
    change-log: db/changelog/master.xml
  jpa:
    hibernate:
      ddl-auto: update

